// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/infobloxopen/atlas-dapr-gateway/pkg/pb/service.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TODO: Structure your own protobuf messages. Each protocol buffer message is a
// small logical record of information, containing a series of name-value pairs.
type VersionResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_02c64595b7f53436, []int{0}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionResponse)(nil), "service.VersionResponse")
}

func init() {
	proto.RegisterFile("github.com/infobloxopen/atlas-dapr-gateway/pkg/pb/service.proto", fileDescriptor_02c64595b7f53436)
}

var fileDescriptor_02c64595b7f53436 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x55, 0x06, 0x0a, 0x5e, 0xa8, 0x32, 0xa0, 0x2a, 0x30, 0xa0, 0x4e, 0x48, 0x10, 0x1b,
	0x95, 0x09, 0x31, 0x15, 0x81, 0xba, 0xa2, 0x0e, 0x0c, 0x6c, 0x97, 0xe4, 0x70, 0x2d, 0x52, 0xdf,
	0xc9, 0x76, 0x53, 0xb2, 0xf2, 0x0a, 0x3c, 0x1a, 0xaf, 0xc0, 0x83, 0xa0, 0x26, 0x8e, 0x54, 0xd1,
	0x89, 0xcd, 0x77, 0xf7, 0xeb, 0xff, 0xf4, 0xff, 0x16, 0x77, 0xda, 0x84, 0xe5, 0x3a, 0x97, 0x05,
	0xad, 0x94, 0xf7, 0xcb, 0xa9, 0x26, 0x05, 0xa1, 0x02, 0x9f, 0x95, 0xc0, 0x2e, 0xd3, 0x10, 0x70,
	0x03, 0x8d, 0xe2, 0x77, 0xad, 0x38, 0x57, 0x1e, 0x5d, 0x6d, 0x0a, 0x94, 0xec, 0x28, 0x50, 0x32,
	0x8c, 0x63, 0x7a, 0xa6, 0x89, 0x74, 0x85, 0xaa, 0x5d, 0xe7, 0xeb, 0x37, 0x85, 0x2b, 0x0e, 0x4d,
	0xa7, 0x4a, 0xcf, 0xe3, 0x11, 0xd8, 0x28, 0xb0, 0x96, 0x02, 0x04, 0x43, 0xd6, 0xc7, 0xeb, 0x6c,
	0x07, 0x8f, 0xb6, 0xa6, 0x86, 0x1d, 0x7d, 0x34, 0x9d, 0x53, 0x91, 0x69, 0xb4, 0x59, 0x0d, 0x95,
	0x29, 0x21, 0xa0, 0xda, 0x7b, 0x44, 0x8b, 0xeb, 0x1d, 0xb1, 0xdf, 0x80, 0xd6, 0xe8, 0x14, 0x71,
	0x0b, 0xd9, 0x07, 0x4e, 0xae, 0xc4, 0xc9, 0x0b, 0x3a, 0x6f, 0xc8, 0x2e, 0xd0, 0x33, 0x59, 0x8f,
	0xc9, 0x58, 0x0c, 0xeb, 0x6e, 0x35, 0x1e, 0x5c, 0x0c, 0x2e, 0x8f, 0x17, 0xfd, 0x38, 0x2d, 0xc5,
	0x68, 0xb6, 0x2d, 0xe3, 0x11, 0xd8, 0xcd, 0xbb, 0x2a, 0x92, 0x67, 0x21, 0xe6, 0x18, 0xa2, 0x47,
	0x72, 0x2a, 0xbb, 0x78, 0xb2, 0xcf, 0x2e, 0x9f, 0xb6, 0xd9, 0xd3, 0xb1, 0xec, 0xbb, 0xfa, 0x43,
	0x9b, 0x8c, 0x3e, 0xbf, 0x7f, 0xbe, 0x0e, 0x44, 0x72, 0xa4, 0x22, 0xe5, 0xe1, 0xe6, 0x55, 0xfe,
	0xe3, 0x13, 0xee, 0x39, 0xcf, 0x0f, 0x5b, 0xda, 0xed, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x68,
	0x98, 0xd4, 0x97, 0xbd, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AtlasDaprGatewayClient is the client API for AtlasDaprGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AtlasDaprGatewayClient interface {
	GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type atlasDaprGatewayClient struct {
	cc *grpc.ClientConn
}

func NewAtlasDaprGatewayClient(cc *grpc.ClientConn) AtlasDaprGatewayClient {
	return &atlasDaprGatewayClient{cc}
}

func (c *atlasDaprGatewayClient) GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/service.AtlasDaprGateway/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AtlasDaprGatewayServer is the server API for AtlasDaprGateway service.
type AtlasDaprGatewayServer interface {
	GetVersion(context.Context, *empty.Empty) (*VersionResponse, error)
}

func RegisterAtlasDaprGatewayServer(s *grpc.Server, srv AtlasDaprGatewayServer) {
	s.RegisterService(&_AtlasDaprGateway_serviceDesc, srv)
}

func _AtlasDaprGateway_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AtlasDaprGatewayServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.AtlasDaprGateway/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AtlasDaprGatewayServer).GetVersion(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _AtlasDaprGateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.AtlasDaprGateway",
	HandlerType: (*AtlasDaprGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _AtlasDaprGateway_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/infobloxopen/atlas-dapr-gateway/pkg/pb/service.proto",
}
